language: go
go:
- 1.10.x
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: NPTP/9bS4G1FCMemQmtI8FjRbWyi1B6o9s2Yuq0QA3AUm0uTQq8D5RA8ynDerSEikY7ZbuvMHWk0+jlPyoDhFEVe36eHCFY0dsqP82nQGjdQJZ26GaRoqhKDLAZHv/z2jm8orIcEIRwAQgHz3P8Ta+BFVJIKcPy62ahkj/ChPItNdto5n0am4U+cTFyn+cx4wIvO+TOJdGRdO496A9ogDEHP2gOqq1rP0vnygTITb9ww609he1x2cGXOWkD8o3z0NtHbsQqzhvDfWoqMvEF+7x9DeCP0sYcoRwvyffXnrX80sUwotW60ayFXRrqgiiTECkCF1hgjRxAGw0uAf+D/6xl7IkbeFG/n5+v8s2Rvngo15D7tX5FrqNjH4ii8PJPUJHzwgAJIG6iM8n1vvSzBbknumcn01cCBcmMuWkuGibcBB7gLC/q8kfv2IrTFKwmCXSLAgcHyCI85GxQc7ek3ICcwv/ajs04sBKSQhVDHEmm+zoewjegene+3TE1Bq2yUgF+2XSX/vRAklgLdQwIiGKf9BH9ShDB/lhqg+JJvHeIfa6jL3AAsUGm7hnolSen4zXiZkLtiigLKidzVdjXKmQqX4nw1OfIDklfwAaYMh3evjvXVTFwl900qBMuJCo8AbaEVGXcaNlX9fcGTrn1eESdWOuM/UK22DymuTHPBtW0=
  file: release/*
  on:
    tags: true