apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: database-secret-config
    type: Opaque
    data:
      username: AzureDiamond
      password: hunter2
  - apiVersion: v1
    kind: Secret
    metadata:
      name: super-duper-secret
    type: Opaque
    data:
      my-key: nononoyes 